//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taekwondo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parent
    {
        public string parentID { get; set; }
        public string fathername { get; set; }
        public string fatheremail { get; set; }
        public string fathermobile { get; set; }
        public string mothername { get; set; }
        public string motheremail { get; set; }
        public string mothermobile { get; set; }
        public string emergencycontact { get; set; }
        public string studentID { get; set; }
    
        public virtual student student { get; set; }
    }
}
