//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taekwondo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentclass
    {
        public string stdclassID { get; set; }
        public string studentID { get; set; }
        public string classID { get; set; }
        public string attendeddate { get; set; }
    
        public virtual classschedule classschedule { get; set; }
        public virtual student student { get; set; }
    }
}
