//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taekwondo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentfee
    {
        public string stdfeeID { get; set; }
        public string studentID { get; set; }
        public string feeID { get; set; }
        public System.DateTime paiddate { get; set; }
    
        public virtual fee fee { get; set; }
        public virtual student student { get; set; }
    }
}
