//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Taekwondo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class studentrank
    {
        public string stdrankID { get; set; }
        public string studentID { get; set; }
        public string rankID { get; set; }
        public string dateachieved { get; set; }
    
        public virtual rank rank { get; set; }
        public virtual student student { get; set; }
    }
}
